# Generated by Django 5.2.5 on 2025-09-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
    ]
