# Generated by Django 5.2.5 on 2025-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0002_remove_skill_proficiency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="skill",
            name="technology",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="aboo.technology"
            ),
        ),
    ]
