# Generated by Django 5.2.5 on 2025-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0003_technology_skill_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
    ]
