# Generated by Django 5.2.5 on 2025-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0004_service_slug_alter_contactmessage_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
