# Generated by Django 5.2.5 on 2025-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0005_alter_service_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="slug",
        ),
        migrations.AddField(
            model_name="service",
            name="challenges",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="conclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="service",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="service",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="solutions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="aboo.technology"),
        ),
    ]
