# Generated by Django 5.2.5 on 2025-09-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0006_remove_service_slug_service_challenges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
