# Generated by Django 5.2.5 on 2025-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboo", "0007_service_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
